# This workflow run the evm tester with proof running enabled.
name: Nightly EVM Tester Proof Run

on:
    schedule:
        - cron: "0 2 * * *"

permissions: read-all

jobs:
    evm_state_tests:
        name: EF EVM state tests with proof run
        runs-on: [matterlabs-ci-runner-high-performance]
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  rustflags: ""
            - name: Setup
              run: |
                  rustup toolchain install
                  rustup set profile minimal
                  cargo install cargo-binutils
            - name: Compile for RISC-V
              working-directory: ./zksync_os
              run: |
                  rustup target add riscv32i-unknown-none-elf
                  cargo install cargo-binutils
                  rustup component add llvm-tools-preview
                  rustup component add rust-src
                  ./dump_bin.sh --type evm-tester
            - name: Download ethereum execution spec tests fixtures
              working-directory: ./tests/evm_tester
              run: |
                  ./download_ethereum_fixtures.sh
            - name: Run EVM state tests
              working-directory: ./tests/evm_tester
              run: cargo run --bin evm-tester --release --features zksync_os_forward_system/no_print -- --proof_run
