name: Update app.bin

on:
    pull_request:
        types: [synchronize, opened]

permissions:
    contents: write
    packages: read
    actions: read
    pull-requests: write

jobs:
    update_app_bin:
        runs-on: [matterlabs-ci-runner]

        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3

            - name: Build fresh app bin
              run: |
                  zksync_os/reproduce/reproduce.sh

            - name: Commit only if protocol_hash changed
              run: |
                  git config user.name  "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

                  if git diff --quiet --exit-code zksync_os/protocol_hash.txt; then
                    echo "protocol_hash unchanged – nothing to commit"
                  else
                    git stash push -m "local-changes"
                    git fetch origin ${{ github.head_ref }}
                    git checkout ${{ github.head_ref }}
                    git stash pop || echo "Nothing to pop"
                    git commit -a -m "chore: auto-update app.bin file"
                    git push origin HEAD:${{ github.head_ref }}
                  fi
